## Question 1
For each of the Theta vectors below, find the decision boundary, and give an example of a point that would get classified as Class 0 and a point that would get classified as Class 1. (There isn't really any Python coding to do here, so you can just type your answers below.)
<ol>
    <li> $\theta =[5,-2]$ </li> 
     <li> $\theta =[5,-2,3]$ </li> 
     <li> $\theta =[5,-2,3,-4]$ </li> 
     <li> $\theta =[5,-2,3,-4,1]$ </li> 
    </ol>

 1) $$ x_1 = \frac{5}{2} $$ <br> Anything < $$\frac{3}{2}$$ is 0 and anything > than is 1 <br>
 2) $$ x_1 = \frac{3}{2}x_2 + \frac{5}{2} $$ <br> $$(0,3)$$ would be 1 and $$(0,0)$$ would be 0<br>
 3) $$ x_1 = \frac{3}{2}x_2 - 2x_3 + \frac{5}{2}$$ <br> $$(0,0,0)$$ will be 0 and $$(-3,2,4)$$ will be 1 <br>
 4) $$ x_1 = \frac{3}{2}x_2 - 2x_3 -\frac{1}{2}x_4+ \frac{5}{2} $$ <br> $$(0,0,0,0)$$ will be 0 and $$(,,,)$$ will be a 1<br>



## Question 2

Compare the three different methods of Scaling/Normalizing data from sklearn on the given $X$ vector. Explain what each technique is doing to normalize the data.


In [258]:
## This cell is just set up.
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
X=np.array([1.0,5,-2,4,-6,7,2,-8,9,0])
X=X.reshape(-1,1)
print(X.shape)

(10, 1)


In [259]:
## Example for first method = StandardScaler
scaler1=StandardScaler()
Xss=scaler1.fit(X)
scaler1.transform(X)

print(scaler1.transform(X))
StandardScaler??


[[-0.03880753]
 [ 0.737343  ]
 [-0.62092042]
 [ 0.54330537]
 [-1.39707095]
 [ 1.12541826]
 [ 0.15523011]
 [-1.78514621]
 [ 1.51349353]
 [-0.23284516]]


(A) What does StandardScaler do? 

Standard Scalar standardizes the features by removing the mean and scaling to unit vectors

standard score of sample x is calculated using <br>

$$ z = (x-u) / s $$  <br>
where u is the mean of the training samples and s is the standard deviation

(B) Explain what the following code is doing and why it is important.

In [260]:
print(scaler1.mean_) # this returns the mean value for each feature in the data.
print(scaler1.scale_)  # returns the feature relative scaling of the data

# these are used when transforming the data back when the fit is done and the data needs to be visualised 


[1.2]
[5.15363949]


(C)  Repeat (A) and (B) as above for MinMaxScaler in place of StandardScaler and explain what 
that method is doing. You'll need to think about what the appropriate parameters are for MinMaxScaler for (B).

In [261]:
## Example for second method = MinMaxScalar
MinMaxScaler??
scaler2=MinMaxScaler()  # leaving default parameters to specify data in range of 0-1 
Xmm=scaler2.fit(X)
scaler2.transform(X)



# (B) Explain what the following code is doing and why it is important.
print(scaler2.min_)  # returns per feature adjustment for minimum 
print(scaler2.scale_)  # per feature relative scaling of the data 
print(scaler2.data_range_)  # per feature range seen in the data
print(Xmm)


[0.47058824]
[0.05882353]
[17.]
MinMaxScaler(copy=True, feature_range=(0, 1))


(A) What does MinMaxScalar do? 

MinMaxScalar transforms the features by scaling each feature to a given range and is given by <br>

$$ X_{std} = \frac{(X - X_{min})} {X_{max}} - X_{min} $$

$$ X_{scaled} = X_{std} * (max - min) + min $$

Min Max Scalar takes arguments of a tuple which specifies the desired range of transformed data. default is (0,1)

## Question 3
Use sklearn to redo your linear regression from HW due Jan 27, Question 3. That is:
<br>
(A) Create an X which contains only the features you used before.
<br>
(B) Drop NaNs and Normalize the data. (Use one of the sklearn functions to do the Normalization now.)
<br>
(C) Perform the Linear Regression using sklearn commands and output your $\theta$ vector.

In [262]:
# Here's data that you used before.
import pandas as pd
URL = 'http://facweb1.redlands.edu/fac/joanna_bieri/machinelearning/LifeExpectancyData.csv'
df = pd.read_csv(URL)
df.drop('Country', axis=1, inplace=True)
df.drop('Year', axis=1, inplace=True)
df.drop('Status', axis=1, inplace=True)
df.describe()

Life expectancy   Adult Mortality  Infant deaths      Alcohol  \
count       2928.000000      2928.000000    2938.000000  2744.000000   
mean          69.224932       164.796448      30.303948     4.602861   
std            9.523867       124.292079     117.926501     4.052413   
min           36.300000         1.000000       0.000000     0.010000   
25%           63.100000        74.000000       0.000000     0.877500   
50%           72.100000       144.000000       3.000000     3.755000   
75%           75.700000       228.000000      22.000000     7.702500   
max           89.000000       723.000000    1800.000000    17.870000   

       percentage expenditure  Hepatitis B       Measles           BMI  \
count             2938.000000  2385.000000    2938.000000  2904.000000   
mean               738.251295    80.940461    2419.592240    38.321247   
std               1987.914858    25.070016   11467.272489    20.044034   
min                  0.000000     1.000000       0.000000     1.000000   
25%                  4.685343    77.000000       0.000000    19.300000   
50%                 64.912906    92.000000      17.000000    43.500000   
75%                441.534144    97.000000     360.250000    56.200000   
max              19479.911610    99.000000  212183.000000    87.300000   

       under-five deaths         Polio  Total expenditure  Diphtheria   \
count         2938.000000  2919.000000         2712.00000  2919.000000   
mean            42.035739    82.550188            5.93819    82.324084   
std            160.445548    23.428046            2.49832    23.716912   
min              0.000000     3.000000            0.37000     2.000000   
25%              0.000000    78.000000            4.26000    78.000000   
50%              4.000000    93.000000            5.75500    93.000000   
75%             28.000000    97.000000            7.49250    97.000000   
max           2500.000000    99.000000           17.60000    99.000000   

          HIV/AIDS            GDP    Population  thinness  1-19 years  \
count  2938.000000    2490.000000  2.286000e+03           2904.000000   
mean      1.742103    7483.158469  1.275338e+07              4.839704   
std       5.077785   14270.169342  6.101210e+07              4.420195   
min       0.100000       1.681350  3.400000e+01              0.100000   
25%       0.100000     463.935626  1.957932e+05              1.600000   
50%       0.100000    1766.947595  1.386542e+06              3.300000   
75%       0.800000    5910.806335  7.420359e+06              7.200000   
max      50.600000  119172.741800  1.293859e+09             27.700000   

       thinness 5-9 years  Income composition of resources    Schooling  
count         2904.000000                      2771.000000  2775.000000  
mean             4.870317                         0.627551    11.992793  
std              4.508882                         0.210904     3.358920  
min              0.100000                         0.000000     0.000000  
25%              1.500000                         0.493000    10.100000  
50%              3.300000                         0.677000    12.300000  
75%              7.200000                         0.779000    14.300000  
max             28.600000                         0.948000    20.700000

In [263]:
# Select just the features you used and the target output in x and y


''' have to drop unnecessary columns with y vec included to ensure the same dimensions after dropping NAs  '''

df.drop(
  ['Infant deaths',
 'Alcohol',
 'percentage expenditure',
 'Hepatitis B',
 'Measles ',
 'BMI',
 'under-five deaths ',
 'Polio',
 'Total expenditure',
 'Diphtheria ',
 'GDP',
 'Population',
 'thinness  1-19 years',
 'thinness 5-9 years',], axis=1, inplace=True) # drops the unwanted features as well as strings 

df.dropna(inplace=True) # have to drop NA's for the X matrix and Y vec together 

y = df['Life expectancy ']  # keep y vec as a series. Not reshaping into col vec
df.drop('Life expectancy ', axis=1, inplace=True)  # now remove y vec from the x matrix 

# Normalize the data 
scalar=MinMaxScaler()
Xmm=scalar.fit(df)  # Do i need to be saving this in a variable

X=scalar.transform(df) # normalized feature set
print(f'Transformed (normalized) df:\n{X[:5]}\n')
print(f'Bottom 5 of X matrix:\n{X[-5:]}\n')
# Check the shape of your normalized data
print(f'Shape of X matrix : {X.shape}\n')
print(f'Shape of y vector: {y.shape}\n')

print(f'y vector:\n{y}')



Transformed (normalized) df:
[[0.36288089 0.         0.50527426 0.48792271]
 [0.37396122 0.         0.5021097  0.48309179]
 [0.36980609 0.         0.49578059 0.47826087]
 [0.37534626 0.         0.48839662 0.47342995]
 [0.37950139 0.         0.47890295 0.4589372 ]]

Bottom 5 of X matrix:
[[1.         0.66336634 0.42932489 0.44444444]
 [0.98891967 0.72475248 0.44092827 0.4589372 ]
 [0.09972299 0.78613861 0.45042194 0.48309179]
 [0.94875346 0.83168317 0.45042194 0.47342995]
 [0.91966759 0.85940594 0.45780591 0.47342995]]

Shape of X matrix : (2768, 4)

Shape of y vector: (2768,)

y vector:
0       65.0
1       59.9
2       59.9
3       59.5
4       59.2
        ... 
2933    44.3
2934    44.5
2935    44.8
2936    45.3
2937    46.0
Name: Life expectancy , Length: 2768, dtype: float64


In [264]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()  # create an object that's easier to work with 
lm.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [265]:
## This is theta_0
print(f'Theta 0, ie. Intercept: {lm.intercept_}\n')
 
print(f'Remaining Thetas, 1 through f: {lm.coef_ }')


Theta 0, ie. Intercept: 53.82224617163827

Remaining Thetas, 1 through f: [-13.80107829 -26.15037411   9.23591552  23.06757498]


## Question 4 
Repeat the above but use the other normalization technique from above. How did the theta parameters change?

In [266]:
# Using Standard Scalar for normalization

# Normalize the data 
std_scalar=StandardScaler()
Xmm=std_scalar.fit(df)
print(Xmm)
X=std_scalar.transform(df) # normalized feature set
print(f'Transformed (normalized) df:\n{X[:5]}\n')
print(f'Bottom 5 of X matrix:\n{X[-5:]}\n')
# Check the shape of your normalized data
print(f'Shape of X matrix : {X.shape}\n')
print(f'Shape of y vector: {y.shape}\n')

print(f'y vector:\n{y}')

StandardScaler(copy=True, with_mean=True, with_std=True)
Transformed (normalized) df:
[[ 0.81311838 -0.32018438 -0.70360648 -0.5677621 ]
 [ 0.87819489 -0.32018438 -0.71782854 -0.59765   ]
 [ 0.8537912  -0.32018438 -0.74627265 -0.62753789]
 [ 0.88632945 -0.32018438 -0.77945746 -0.65742579]
 [ 0.91073314 -0.32018438 -0.82212363 -0.74708949]]

Bottom 5 of X matrix:
[[ 4.55501757  6.13838804 -1.04493586 -0.83675319]
 [ 4.48994106  6.73604698 -0.99278831 -0.74708949]
 [-0.73244867  7.33370592 -0.95012214 -0.59765   ]
 [ 4.25403872  7.7771303  -0.95012214 -0.65742579]
 [ 4.08321289  8.04704079 -0.91693734 -0.65742579]]

Shape of X matrix : (2768, 4)

Shape of y vector: (2768,)

y vector:
0       65.0
1       59.9
2       59.9
3       59.5
4       59.2
        ... 
2933    44.3
2934    44.5
2935    44.8
2936    45.3
2937    46.0
Name: Life expectancy , Length: 2768, dtype: float64


In [267]:
lm.fit(X,y)
## This is theta_0
print(f'Theta 0, ie. Intercept: {lm.intercept_}\n')
 
print(f'Remaining Thetas, 1 through f: {lm.coef_ }')


Theta 0, ie. Intercept: 69.34956647398845

Remaining Thetas, 1 through f: [-2.34985774 -2.68593069  2.05508811  3.72851774]


## Question 5
Repeat the above but do not normalize the data before calling the LinearRegression() function. Instead call the LinearRegression() function with 
lm = LinearRegression(normalize=True). How did the theta parameters change? What is this doing?

In [268]:
'''Using the same data as before but normalizing it with the built in normalization in linear regression from sklearn'''

df = pd.read_csv(URL)
df.drop('Country', axis=1, inplace=True)
df.drop('Year', axis=1, inplace=True)
df.drop('Status', axis=1, inplace=True)
df.describe()

''' have to drop unnecessary columns with y vec included to ensure the same dimensions after dropping NAs  '''

df.drop(
  ['Infant deaths',
 'Alcohol',
 'percentage expenditure',
 'Hepatitis B',
 'Measles ',
 'BMI',
 'under-five deaths ',
 'Polio',
 'Total expenditure',
 'Diphtheria ',
 'GDP',
 'Population',
 'thinness  1-19 years',
 'thinness 5-9 years',], axis=1, inplace=True) # drops the unwanted features as well as strings 

df.dropna(inplace=True) # have to drop NA's for the X matrix and Y vec together 

y = df['Life expectancy ']  # keep y vec as a series. Not reshaping into col vec
df.drop('Life expectancy ', axis=1, inplace=True)  # now remove y vec from the x matrix 



In [269]:
lm = LinearRegression(normalize=True)
lm.fit(df,y)

## This is theta_0
print(f'Theta 0, ie. Intercept: {lm.intercept_}\n')
 
print(f'Remaining Thetas, 1 through f: {lm.coef_ }')


Theta 0, ie. Intercept: 53.893144157550296

Remaining Thetas, 1 through f: [-0.01911507 -0.51782919  9.74252692  1.1143756 ]


## Question 6
For your favorite normalization technique, pick a different set of 3-5 features and see how the theta parameters change. 

In [270]:
'''Using the same data as before but normalizing it with the built in normalization in linear regression from sklearn'''

df = pd.read_csv(URL)
df.drop('Country', axis=1, inplace=True)
df.drop('Year', axis=1, inplace=True)
df.drop('Status', axis=1, inplace=True)
df.describe()
''' have to drop unnecessary columns with y vec included to ensure the same dimensions after dropping NAs  '''

df.drop(
  [ 
   'Adult Mortality',
   'Alcohol',
   'percentage expenditure',
   'BMI',
   'under-five deaths ',
   'Polio',
   'Total expenditure',
   'Diphtheria ',
   'HIV/AIDS',
   'GDP',
   'Population',
   'thinness  1-19 years',
   'Income composition of resources',
   'Schooling'], axis=1, inplace=True) # drops the unwanted features as well as strings 
'''Keeping: Measles, Hepatitis B, Infant deaths, thinness 5-9 years '''
df.dropna(inplace=True) # have to drop NA's for the X matrix and Y vec together 

y = df['Life expectancy ']  # keep y vec as a series. Not reshaping into col vec
df.drop('Life expectancy ', axis=1, inplace=True)  # now remove y vec from the x matrix 
print(df.columns)


Index(['Life expectancy ', 'Infant deaths', 'Hepatitis B', 'Measles ',
       'thinness 5-9 years'],
      dtype='object')


In [271]:
''' Using existing lm object but changing the fit to the new data.'''
lm.fit(df,y)

## This is theta_0
print(f'Theta 0, ie. Intercept: {lm.intercept_}\n')
 
print(f'Remaining Thetas, 1 through f: {lm.coef_ }')


Theta 0, ie. Intercept: 68.24375481302054

Remaining Thetas, 1 through f: [ 4.68246988e-03  7.09097110e-02 -2.40303209e-05 -8.48337112e-01]
